version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: soul4927/s-talk_frontend:latest
    ports:
      - '3000:3000'
    command: ['yarn', 'start']
